// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIiT6g4HerH4zDGIhIsVUvcbxGGjND4Vo',
    appId: '1:439791773449:android:f1b2ae5d9c24dedd2995d8',
    messagingSenderId: '439791773449',
    projectId: 'flutter-nova-v2',
    storageBucket: 'flutter-nova-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZ9qV8kwtUN-kwkj8Lekgv7fYEw8aLXA',
    appId: '1:439791773449:ios:f734533dacdcab992995d8',
    messagingSenderId: '439791773449',
    projectId: 'flutter-nova-v2',
    storageBucket: 'flutter-nova-v2.appspot.com',
    androidClientId: '439791773449-vhubpd70fjfo5iqg05513vkh1l35bno9.apps.googleusercontent.com',
    iosClientId: '439791773449-0ejp0a49erudvp4sm3ltj8eujru5rv33.apps.googleusercontent.com',
    iosBundleId: 'com.denuwan.novaV2',
  );
}
